version: '3'

services:
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./services/api
    links:
      - db
  db:
    build:
      dockerfile: Dockerfile.dev
      context: ./services/db
    volumes:
        - .data/mdata:/data/db
  nginx:
      restart: always
      build:
        dockerfile: Dockerfile.dev
        context: ./services/nginx
      ports:
        - '3051:80'
